version: '3.8'

volumes:
  prometheus_data:
  grafanadata:
  pgdata:

networks:
  grpc-network:
    external: true

services:
  db:
    image: postgres:13-alpine
    container_name: userBD
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "userdb"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d userdb" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - grpc-network


  http-server:
    build:
      context: .
      dockerfile: Dockerfile

    image: docker.io/akbae/ci-http:latest

    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-db.sh","db", "user", "12345", "userdb", "./userServer"]
    networks:
      - grpc-network

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    networks:
      - grpc-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    networks:
      - grpc-network


  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - grpc-network



  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
    networks:
      - grpc-network



