global:
  scrape_interval: 2s
  evaluation_interval: 2s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "http-server:9090" ]

  - job_name : "user_app"
    static_configs:
      - targets: [ "http-server:8080" ]

  - job_name: "bike_domain"
    static_configs:
        - targets: [ "http-server:8080" ]


