name: Deploy Docker Compose via SSH

on:
  push:
    branches: [main]  # Trigger on push to main branch
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (optional, if building images locally)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main' && success()
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Deploy with docker-compose
        run: |
          docker compose -f deployments/docker-compose.yml up -d
